### PR TITLE
Query api

### LINKED ISSUE #14: Add QueryAPI
- [ ] check v1 client: https://github.com/influxdata/influxdb-ruby#querying
- [ ] add light way `query_api` (synchronous) that will follow structure in our others client
- [ ] create `FluxRecord`, `FluxTable`, ... as is in other clients

### LINKED ISSUE #16: Query method: read_body called twice
``` console
irb(main):039:0> result = query_api.query(query: 'from(bucket:"' + bucket + '") |> range(start: 1970-01-01T00:00:00.000000001Z) |> last()')
Traceback (most recent call last):
        4: from bin/console:14:in `<main>'
        3: from (irb):39
        2: from /Users/giovannelli/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/influxdb-client-ruby-3c32bcbe6afb/lib/influxdb2/client/query_api.rb:60:in `query'
        1: from /Users/giovannelli/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http/response.rb:198:in `read_body'
IOError (Net::HTTPOK#read_body called twice)
```

The issue seems to be here:

``` ruby
# lib/influxdb2/client/query_api.rb:60
...
      response.read_body do |chunk|
        parser.parse(chunk)
      end
...
```
The following patch works, but probably you prefer to keep reading responses in chunk.

``` ruby
parser.parse(response.body)
```

Are you planning to add a query DSL instead of using the raw query? And are you planning to format the response some how? Just to avoid doing the work twice.

Thank you,
Duccio

### PR DESCRIPTION
**Pull request by rolincova**
Closes #14
Closes #16 

_Briefly describe your proposed changes:_

  - [x] CHANGELOG.md updated
  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: test/influxdb/query_api_integration_test.rb [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+# THE SOFTWARE.
+
+require 'test_helper'
+
+class WriteApiTest < MiniTest::Test
```
Comment (bednar) [inline test/influxdb/query_api_integration_test.rb]: Rename to QueryApiIntegrationTest

File: test/influxdb/query_api_test.rb [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+# THE SOFTWARE.
+
+require 'test_helper'
+
+class WriteApiTest < MiniTest::Test
```
Comment (bednar) [inline test/influxdb/query_api_test.rb]: Rename to QueryApiTest

File: lib/influxdb2/client/flux_table.rb [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+    def initialize(table, values: nil)
+      @table = table
+      @values = values || {}
+    end
+    attr_reader :table, :values
+    attr_writer :table
+
+    # @param [String] key
+    # @param [Object] value
+    def add_value(key:, value:)
```
Comment (bednar) [inline lib/influxdb2/client/flux_table.rb]: Unused -> remove

File: lib/influxdb2/client/flux_csv_parser.rb [hunk 4]
```diff
@@ -0,0 +1,210 @@
...
+          raise FluxQueryError.new(error, reference_value.nil? || reference_value.empty? ? 0 : reference_value.to_i)
+        end
+
+        parse_line(csv)
+      end
+
+      @tables
+    end
+
+    def parse_line(csv)
```
Comment (bednar) [inline lib/influxdb2/client/flux_csv_parser.rb]: Transform to private method

File: lib/influxdb2/client/flux_csv_parser.rb [hunk 5]
```diff
@@ -0,0 +1,210 @@
...
+        FluxCsvParser.add_groups(@table, csv)
+
+      elsif token == '#default'
+        FluxCsvParser.add_default_empty_values(@table, csv)
+      else
+        _parse_values(csv)
+      end
+    end
+
+    def self.add_data_types(table, data_types)
```
Comment (bednar) [inline lib/influxdb2/client/flux_csv_parser.rb]: Transform to private and instance method

File: lib/influxdb2/client/flux_csv_parser.rb [hunk 6]
```diff
@@ -0,0 +1,210 @@
...
+      (1..data_types.length - 1).each do |index|
+        column_def = InfluxDB2::FluxColumn.new(index: index - 1, data_type: data_types[index])
+        table.columns.push(column_def)
+      end
+    end
+
+    def self.add_groups(table, csv)
```
Comment (bednar) [inline lib/influxdb2/client/flux_csv_parser.rb]: Transform to private and instance method

File: lib/influxdb2/client/flux_csv_parser.rb [hunk 7]
```diff
@@ -0,0 +1,210 @@
...
+      i = 1
+
+      table.columns.each do |column|
+        column.group = csv[i] == 'true'
+        i += 1
+      end
+    end
+
+    def self.add_default_empty_values(table, default_values)
```
Comment (bednar) [inline lib/influxdb2/client/flux_csv_parser.rb]: Transform to private and instance method

File: lib/influxdb2/client/flux_csv_parser.rb [hunk 8]
```diff
@@ -0,0 +1,210 @@
...
+      i = 1
+
+      table.columns.each do |column|
+        column.default_value = default_values[i]
+        i += 1
+      end
+    end
+
+    def self.add_column_names_and_tags(table, csv)
```
Comment (bednar) [inline lib/influxdb2/client/flux_csv_parser.rb]: Transform to private and instance method
